server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
  profiles:
    # 这里指定读取本地配置（一共可以读取两部分，本地和github）
    # 配置文件获取路径
    active: native
  cloud:
    config:
      server:
        native:
          # 本地配置文件路径
          search-locations: classpath:/shared