server:
  port: 8010


spring:
  application:
    # spring.application.name ： 当前服务注册在 Eureka Server 上的名称。
    name: provider

eureka:
  client:
    service-url:
      # eureka.client.service-url.defaultZone ： 注册中⼼的访问地址。
      defaultZone: http://localhost:8761/eureka/
  instance:
    # eureka.instance.prefer-ip-address ： 是否将当前服务的 IP 注册到 Eureka Server。
    prefer-ip-address: true